import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

import './globals.css';

// ** Store Imports
import { Providers } from '@/store/Provider';
import Template from './template';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn('max-w-screen', inter.className)}>
        <Template>
          <Toaster />
          <Providers>{children}</Providers>
        </Template>
      </body>
    </html>
  );
}
