import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

// ** Store Imports
import { Providers } from '@/store/Provider';
import Template from './template';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Template>
          <Providers>{children}</Providers>
        </Template>
      </body>
    </html>
  );
}
